### PR TITLE
Add a better infobox sound

### PR DESCRIPTION
**Pull request by ComputeLinux**

### CODE REVIEW

**Comment by RogueAI42** [comment]
3beepvirus.wav isn't supposed to be the infobox sound... infobox.wav is...

**Comment by ComputeLinux** [comment]
fixed that

**Comment by MichaelTheShifter** [comment]
...whoa did this get merged? I really don't like the fact that the signature ShiftOS infobox sound is gone...

**Comment by ComputeLinux** [comment]
it doesnt play for somereason anyways so

**Pull request merged**
