### PR TITLE
calc adding

### PR DESCRIPTION
**Pull request by lempamo**

### CODE REVIEW

**Comment by ComputeLinux** [comment]
you don't have to spam PRs, why don't you just finish it

**Comment by ComputeLinux** [comment]
whoops

**Comment by aren-cllc** [comment]
Let's just keep this PR open so we don't have to constantly accept pull requests about one app. You can just keep pushing updates to your fork at lempamo/ShiftOS-lempfork and they'll automagically get added to this pull request. Once you're done, you can just ping me and I'll merge if AppVeyor is ok with it

**Comment by aren-cllc** [comment]
I'll close it for now until you finish the calculator, ping me on discord if you REALLY want it merged

**Comment by aren-cllc** [comment]
Merged in #92

**Pull request closed without merging**
