### PR TITLE
FIX THE OTHER DAMN ISSUE

### PR DESCRIPTION
**Pull request by craftxbox**

### CODE REVIEW

**Comment by wowmom98** [comment]
would be nice if you gave a description of what you actually fixed

**Comment by aren-cllc** [comment]
I assume he made the pong paddles upgrade actually, well, upgrade the paddle size. Just a guess though

**Comment by wowmom98** [comment]
and plus appveyor build didnt even work

**Comment by aren-cllc** [comment]
Actually, @craftxbox You could keep it open, fix the build error, then commit to the patch-2 branch

**Pull request closed without merging**
